# Edition
edition = "2024"

# Line width and wrapping
max_width = 120
use_small_heuristics = "Max"

# Indentation and whitespace
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Imports
reorder_imports = true

# Functions and methods
fn_params_layout = "Tall"
fn_call_width = 60
force_explicit_abi = true

# Control flow
match_block_trailing_comma = false

# Chains
chain_width = 60

# Types and structs
use_field_init_shorthand = true
merge_derives = true

# Miscellaneous
remove_nested_parens = true
use_try_shorthand = true