# Axum server
serve_host = "127.0.0.1"
serve_port = 3000

# Cors
allow_cors_origins = ["https://backendery.digital", "http://127.0.0.1"]

# Email's
from_mailbox = "Backendery <hi@backendery.digital>"
to_mailbox = "Backendery <hi@backendery.digital>"

# Retry
retry_count = 2
retry_timeout = 50

# Router
body_limit = 4
concurrency_limit = 32

# Governor
period_seconds_limit = 60
burst_limit = 3

# Smpt
smtp_connection_timeout = 5000
