---
name: Deploy Rust app to Shuttle

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: shuttle
    env:
      SHUTTLE: 'true'
      SHUTTLE_DEBUG: 'false'
      RUSTUP_TOOLCHAIN: '1.86.0'
      RUST_LOG: 'INFO'
      RUST_VERSION: '1.86.0'
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJECT_ID }}
          cargo-shuttle-version: '0.48.2'
          secrets: |
            sentry_dsn = '${{ secrets.SENTRY_DSN }}'
            sentry_environment = '${{ secrets.SENTRY_ENVIRONMENT }}'
            smtp_addr = '${{ secrets.SMTP_ADDR }}'
            smtp_auth = '${{ secrets.SMTP_AUTH }}'
